### ISSUE TITLE
why was returning count of items dropped in getPriceList function.

### ISSUE THREAD

**Issue by VVILD** [OPSkins/node-opskins-api#1]
Earlier there used to be a count variable as well in getPriceList corresponding to the number of items sold that day . It would really be helpful if you can add that to estimate the correct prices of the item .

**Comment by DoctorMcKay** [comment]
We don't have any plans to restore this at this time, but v1.3.0 updates `getPriceList` to use GetPriceList v2, which includes much more pricing data which allows you to get a better idea for the item's true price.

**Comment by VVILD** [comment]
thanks for the update its really helpful . how are you normalising it btw ? what formula do u use to normalise it ?

**Comment by rannmann** [comment]
We take the mean + standard deviation for each day, and then re-average with just those within `2 * stddev`.  _As a quick reminder, a single standard deviation is about 68% of the middle values within a set. Two standard deviations includes something like 94% of all values. That means we're dropping about 6% of outliers in total, above and below the average._

The "normalized" data refers to values within the set that excludes the outliers. That means the values show:

* Max - Actual maximum price for the day, unfiltered
* Normalized Max - Maximum price within two standard deviations of total mean (Max price within `mean + stdDev`)
* Average - Mean price withing two standard deviations of total mean
* Normalized Min - Minimum price within two standard deviations of total mean (Min price within `mean - stdDev`)
* Min - Actual minimum price for the day, unfiltered
