### ISSUE TITLE
refusing to install .

### ISSUE THREAD

**Issue by Dwight21** [OPSkins/node-opskins-api#12]
![image](https://user-images.githubusercontent.com/23622187/34294555-fa12ffe8-e743-11e7-9abe-f0fa6976f37f.png)

whats error is this ?

**Comment by renanbastos93** [comment]
Hey,

you tried install with mode admin?

**Comment by DoctorMcKay** [comment]
Sounds like you downloaded the repository (I see the download bar in your browser), extracted it, entered the directory, then tried to install it from npm. Which would mean you're installing it as a dependency of itself, which npm refuses to allow.

**Comment by Dwight21** [comment]
ive extract it sir already then put it in the directory but sad for me same issue

**Comment by Dwight21** [comment]
![image](https://user-images.githubusercontent.com/23622187/34355612-b76f26a4-ea71-11e7-8b89-b84238004a23.png)
:(

**Comment by renanbastos93** [comment]
@Dwight21 , 

Dude, you will have create new project with the commands bellow.

```bash
mkdir opSkinsTest
cd opSkinsTest/
npm init
npm i -S @opskins/api
```
Case it asks admin, you have that execute in mode admin.

See ya

**Comment by Dwight21** [comment]
![image](https://user-images.githubusercontent.com/23622187/34357138-64cb834e-ea7f-11e7-83f1-1bd5297ad9eb.png)
what's error is this?

**Comment by Dwight21** [comment]
![image](https://user-images.githubusercontent.com/23622187/34357211-0fa2383a-ea80-11e7-9c64-106cb3d288be.png)
another one

**Comment by renanbastos93** [comment]
Man, this warning is normally. Here this function this module. I did test now.
