### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by adz13** [OPSkins/node-opskins-api#13]
C:\Users\User>npm install @opskins/api
C:\Users\User
`-- @opskins/api@1.4.2

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\package.j
son'
npm WARN User No description
npm WARN User No repository field.
npm WARN User No README data
npm WARN User No license field.

what do i do?

**Comment by mkom99** [comment]
`npm init` before installing modules

**Comment by DoctorMcKay** [comment]
Those are only warnings. It still installed.

**Comment by adz13** [comment]
Thank you :)
