### ISSUE TITLE
Withdraw extension

### ISSUE THREAD

**Issue by MattRh** [OPSkins/node-opskins-api#20]
In the method [IInventory_Withdraw_v1](https://docs.opskins.com/public/en.html#IInventory_Withdraw_v1) there is possibility to withdraw items to other accounts, rather than current one. I can't find any method for that in current implementation. Can you add it?

**Comment by DoctorMcKay** [comment]
That functionality needs to be pre-approved on an account before it's used. It won't be added to this module.
