### ISSUE TITLE
Search method is not working?

### ISSUE THREAD

**Issue by arnaspecelis** [OPSkins/node-opskins-api#23]
I believe something is wrong here since this code returns following error

`return opskins.searchAsync("730_2", "redline").then(function (data) {
                console.log(data);
            })`

> @opskins/api/interfaces/ISales.js:134
                        callback(err);
                        ^
> TypeError: callback is not a function

and any other method used by the same way works well. any ideas?

**Comment by DoctorMcKay** [comment]
Per [the documentation](https://github.com/OPSkins/node-opskins-api#searchparams-callback), the first parameter needs to be an object. Something like:

```js
opskins.searchAsync({"app": "730_2", "search_item": "redline"})
```
